### PR TITLE
[FJTN-55] download report

### PR DESCRIPTION
**Pull request by phumipatc**
The report consists of the following fields
- "ID"
- "Reservation ID",
- "Room ID"
- "Space ID"
- "Space Name"
- "Status"
- "Start Datetime"
- "End Datetime"

### CODE REVIEW

**Review by kyrov — APPROVED** [review]
The code look good to me

**Comment by phumipatc** [comment]
@pottersirawit ถ้าว่างฝากดูอันนี้ ถ้าโอเค approve then merge เลย

**Comment by kyrov** [comment]
-change field name in participant from type to role
-add field room_name

**Review by Tinnaung — APPROVED** [review]
look good to me

**Pull request merged**
